name: Serverless Functions CD
on:
  push:
    branches: ["main"]
    paths:
      - "functions/**"
      - "!*.md"

env:
  PROJECT_ID: ${{secrets.GCP_PROJECT_ID}}

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install node modules
        run: |
          cd functions

      - name: Deploy to Firebase via Firebase
        uses: BIGG-Kaymo/deploy-firebase-functions@v1.0.1
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
