name: Serverless Functions CD
on:
  push:
    branches: ["main"]
    paths:
      - "functions/**"
      - "!*.md"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"
    defaults:
      run:
        working-directory: "functions"

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: "yarn"
          cache-dependency-path: "**/yarn.lock"

      - name: Install project dependencies
        run: yarn install --prefer-offline --frozen-lockfile

      - name: Build
        run: yarn build

  deploy:
    name: Deploy to Firebase
    needs: build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "functions"

    steps:
      - name: Deploy to Cloud Functions via Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only functions
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          PROJECT_ID: ${{secrets.GCP_PROJECT_ID}}
          PROJECT_PATH: ./src
